name: Build Android AAB
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          unzip DopoCapsule.zip -d extracted_code
          cd extracted_code
          flutter pub get
          flutter build appbundle --release
      - uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: extracted_code/build/app/outputs/bundle/release/app-release.aab
